-- Seed data: starter beverage item list (from the existing Excel template's
-- Cost Centre List tab), loaded identically into all three lodges as a
-- starting point. Edit names/categories/min-max per lodge afterwards --
-- item lists are fully separate per location_id, so changes to one lodge
-- do not affect the others.

insert into bev_items (location_id, name, category, count_unit, min_units, max_units) values
  ('ZC', 'Beer - Amstel Lager - 440ml', 'Beer', 'ea', 24, 72),
  ('ZC', 'Beer - Amstel Lite - 440ml', 'Beer', 'ea', 24, 72),
  ('ZC', 'Beer - Black Label - 330ml', 'Beer', 'ea', 24, 72),
  ('ZC', 'Beer - Black Label - 500ml', 'Beer', 'ea', 24, 72),
  ('ZC', 'Beer - Corona - 340ml', 'Beer', 'ea', 24, 72),
  ('ZC', 'Beer - Castle Light - 340ml (Bottle)', 'Beer', 'ea', 24, 72),
  ('ZC', 'Beer - Castle Light - 500ml', 'Beer', 'ea', 24, 72),
  ('ZC', 'Beer - Hansa Pilsner - 340ml (Bottle)', 'Beer', 'ea', 24, 72),
  ('ZC', 'Beer - Heineken - 330ml (Bottle)', 'Beer', 'ea', 24, 72),
  ('ZC', 'Beer - Heineken 0% alcohol', 'Beer', 'ea', 24, 72),
  ('ZC', 'Beer - Heineken - 440ml (Can)', 'Beer', 'ea', 24, 72),
  ('ZC', 'Beer - St Louis Export/ Lager - 340ml (Can)', 'Beer', 'ea', 24, 72),
  ('ZC', 'Beer - St Louis Export/ Lager - 330ml', 'Beer', 'ea', 24, 72),
  ('ZC', 'Beer - Windhoek Draught - 440ml (Can)', 'Beer', 'ea', 24, 72),
  ('ZC', 'Beer - Windhoek Lager - 440ml (Can)', 'Beer', 'ea', 24, 72),
  ('ZC', 'Beer - Windhoek Lager - 330ml (Bottle)', 'Beer', 'ea', 24, 72),
  ('ZC', 'Cider - Brutal fruit - 500ml', 'Cider', 'ea', 24, 72),
  ('ZC', 'Cider - Savannah Dry - 330ml (Bottle)', 'Cider', 'ea', 24, 72),
  ('ZC', 'Cider - Savannah Dry 0% alcohol', 'Cider', 'ea', 24, 72),
  ('ZC', 'Cider - Hunters Dry - 330ml', 'Cider', 'ea', 24, 72),
  ('ZC', 'Cider - Hunters Dry - 500ml', 'Cider', 'ea', 24, 72),
  ('ZC', 'Cider - Hunters Gold - 330ml (Bottle)', 'Cider', 'ea', 24, 72),
  ('ZC', 'Cider - Hunters Gold - 440ml', 'Cider', 'ea', 24, 72),
  ('ZC', 'Cordial - Grenadine - 750ml', 'Cordial', 'ea', 24, 72),
  ('ZC', 'Cordial - Roses Kola Tonic - 750ml', 'Cordial', 'ea', 24, 72),
  ('ZC', 'Cordial - Roses Lime - 750ml', 'Cordial', 'ea', 24, 72),
  ('ZC', 'Cordial - Roses Passion Fruit - 750ml', 'Cordial', 'ea', 24, 72),
  ('ZC', 'Red Wine - The Den"Painted Wolf"Shiraz - 750ml', 'Red Wine', 'ea', 24, 72),
  ('ZC', 'Red Wine - The Den"Painted Wolf"Cabernet Sauv - 750 ml', 'Red Wine', 'ea', 24, 72),
  ('ZC', 'Red Wine - Chocolate Block - 750 ml (Bottle)', 'Red Wine', 'ea', 24, 72),
  ('ZC', 'Red Wine - Fat Bastard Cabanet Sauvignon - 750ml (Bottle)', 'Red Wine', 'ea', 24, 72),
  ('ZC', 'Red Wine - Fat Bastard Merlot - 750ml (Bottle)', 'Red Wine', 'ea', 24, 72),
  ('ZC', 'Red Wine - Robertson Pinotage - 750ml (Bottle)', 'Red Wine', 'ea', 24, 72),
  ('ZC', 'Red Wine - Fat Bastard Shiraz - 750ml (Bottle)', 'Red Wine', 'ea', 24, 72),
  ('ZC', 'Red Wine - The Den "Painted Wolf"Chenin Blanc - 750ml (Bottle)', 'Red Wine', 'ea', 24, 72),
  ('ZC', 'Red Wine - The Den "Painted Wolf"Dry Rose - 750ml (Bottle)', 'Red Wine', 'ea', 24, 72),
  ('ZC', 'Red Wine - The Den"Painted Wolf"Pinotage - 750ml', 'Red Wine', 'ea', 24, 72),
  ('ZC', 'Red Wine - Rupert & Rothschildt Classique - 750ml (Bottle)', 'Red Wine', 'ea', 24, 72),
  ('ZC', 'Red Wine - Protea Rose - 750ml (Bottle)', 'Red Wine', 'ea', 24, 72),
  ('ZC', 'Red Wine - JC Le Roux- 750ml (Bottle)', 'Red Wine', 'ea', 24, 72),
  ('ZC', 'Red Wine - Chapel Rose - -750ml', 'Red Wine', 'ea', 24, 72),
  ('ZC', 'Red Wine - Namaqua Rose - 5l', 'Red Wine', 'ea', 24, 72),
  ('ZC', 'White Wine - La Motte Sauv Blanc - 750ml (Bottle)', 'White Wine', 'ea', 24, 72),
  ('ZC', 'White Wine - Warwick F/Lady Sauv Blanc- 750ml (Bottle)', 'White Wine', 'ea', 24, 72),
  ('ZC', 'White Wine - Fat Bastard Chardonnay - 750ml (Bottle)', 'White Wine', 'ea', 24, 72),
  ('ZC', 'White Wine - Fat Bastard Sauv Blanc - 750ml (Bottle)', 'White Wine', 'ea', 24, 72),
  ('ZC', 'White Wine - Van Loveren Chardonnay - 750ml (Bottle)', 'White Wine', 'ea', 24, 72),
  ('ZC', 'White Wine - Moet&Chandon Brut Non Vintage - 750ml (Bottle)', 'White Wine', 'ea', 24, 72),
  ('ZC', 'White Wine - Porcupine Ridge Chardonnay - 750ml (Bottle)', 'White Wine', 'ea', 24, 72),
  ('ZC', 'White Wine - Porcupine Ridge Sauv Blanc - 750ml (Bottle)', 'White Wine', 'ea', 24, 72),
  ('ZC', 'White Wine - Simonsig Chenin Blanc - 750ml (Bottle)', 'White Wine', 'ea', 24, 72),
  ('ZC', 'White Wine - Van Loveren Sauv Blanc - 750ml (Bottle)', 'White Wine', 'ea', 24, 72),
  ('ZC', 'White Wine - 0% simonsig Kaapse vonkel', 'White Wine', 'ea', 24, 72),
  ('ZC', 'White Wine - Simonsvelei Brut - 750ml (Bottle)', 'White Wine', 'ea', 24, 72),
  ('ZC', 'White Wine - Springfield Life From Stone Sauvignon Blanc - 750ml (Bottle)', 'White Wine', 'ea', 24, 72),
  ('ZC', 'Soft Drinks - Appletizer - 330ml (Can)', 'Soft Drinks', 'ea', 24, 72),
  ('ZC', 'Soft Drinks - Coke - 330ml (Can)', 'Soft Drinks', 'ea', 24, 72),
  ('ZC', 'Soft Drinks - Coke Light/Zero - 330ml (Can)', 'Soft Drinks', 'ea', 24, 72),
  ('ZC', 'Soft Drinks - Dry Lemon - 200ml (Can)', 'Soft Drinks', 'ea', 24, 72),
  ('ZC', 'Soft Drinks - Ice Tea Peach - 300ml', 'Soft Drinks', 'ea', 24, 72),
  ('ZC', 'Soft Drinks - Fanta Orange - 330ml (Can)', 'Soft Drinks', 'ea', 24, 72),
  ('ZC', 'Soft Drinks - Fanta Orange - 440ml', 'Soft Drinks', 'ea', 24, 72),
  ('ZC', 'Soft Drinks - Fanta Pineapple - 330ml', 'Soft Drinks', 'ea', 24, 72),
  ('ZC', 'Soft Drinks - Ginger Ale - 200ml (Can)', 'Soft Drinks', 'ea', 24, 72),
  ('ZC', 'Soft Drinks - Cream Soda - 300ml', 'Soft Drinks', 'ea', 24, 72),
  ('ZC', 'Soft Drinks - Just Ginger - Gemere - 250ml', 'Soft Drinks', 'ea', 24, 72),
  ('ZC', 'Soft Drinks - Stoney Ginger Beer - 2ltr', 'Soft Drinks', 'ea', 24, 72),
  ('ZC', 'Soft Drinks - Lemonade - 200ml (Can)', 'Soft Drinks', 'ea', 24, 72),
  ('ZC', 'Soft Drinks - Grapetiser', 'Soft Drinks', 'ea', 24, 72),
  ('ZC', 'Soft Drinks - Liquifruit - 330ml (Can)', 'Soft Drinks', 'ea', 24, 72),
  ('ZC', 'Soft Drinks - Soda - 200ml (Can)', 'Soft Drinks', 'ea', 24, 72),
  ('ZC', 'Soft Drinks - Sprite - 330ml', 'Soft Drinks', 'ea', 24, 72),
  ('ZC', 'Soft Drinks - Stoney Ginger Beer - 330ml (Can)', 'Soft Drinks', 'ea', 24, 72),
  ('ZC', 'Soft Drinks - Tonic - 200ml (Can)', 'Soft Drinks', 'ea', 24, 72),
  ('ZC', 'Soft Drinks - Energade/sport drink', 'Soft Drinks', 'ea', 24, 72),
  ('ZC', 'Spirits - Amarula - 750ml', 'Spirits', 'ea', 24, 72),
  ('ZC', 'Spirits - Amarula - 375ml', 'Spirits', 'ea', 24, 72),
  ('ZC', 'Spirits - Amarula - Tot', 'Spirits', 'ea', 24, 72),
  ('ZC', 'Spirits - Brandy Klipdrift - Tot', 'Spirits', 'ea', 24, 72),
  ('ZC', 'Spirits - Brandy KWV - Tot', 'Spirits', 'ea', 24, 72),
  ('ZC', 'Spirits - Brandy Richelieu - Tot', 'Spirits', 'ea', 24, 72),
  ('ZC', 'Spirits - Bombay Gin - 750ml - Tots', 'Spirits', 'ea', 24, 72),
  ('ZC', 'Spirits - Gin Gordon''s - 750ml', 'Spirits', 'ea', 24, 72),
  ('ZC', 'Spirits - Red Heart Rum - 750ml', 'Spirits', 'ea', 24, 72),
  ('ZC', 'Spirits - Hennessy - 750 ml', 'Spirits', 'ea', 24, 72),
  ('ZC', 'Spirits - Whiskey - Jack Daniels - 750 ml', 'Spirits', 'ea', 24, 72),
  ('ZC', 'Spirits - Glenfiddich 12 Year', 'Spirits', 'ea', 24, 72),
  ('ZC', 'Spirits - Johnnie Walker Black - 750ml', 'Spirits', 'ea', 24, 72),
  ('ZC', 'Spirits - Jagermeister - 750ml - Tot', 'Spirits', 'ea', 24, 72),
  ('ZC', 'Spirits - Okavango Gin - 750ml', 'Spirits', 'ea', 24, 72),
  ('ZC', 'Spirits - Pushkin vodka - 750ml', 'Spirits', 'ea', 24, 72),
  ('ZC', 'Spirits - Rum Captain Morgan Dark', 'Spirits', 'ea', 24, 72),
  ('ZC', 'Spirits - Tanqueray', 'Spirits', 'ea', 24, 72),
  ('ZC', 'Spirits - Vodka, Smirnoff', 'Spirits', 'ea', 24, 72),
  ('ZC', 'Spirits - Whiskey Bell''s', 'Spirits', 'ea', 24, 72),
  ('ZC', 'Spirits - Whiskey Famous Grouse', 'Spirits', 'ea', 24, 72),
  ('ZC', 'Spirits - Whiskey J&B', 'Spirits', 'ea', 24, 72),
  ('ZC', 'Spirits - Whiskey- Bacardi White Rum 750ml', 'Spirits', 'ea', 24, 72),
  ('ZC', 'Spirits - Whiskey Jameson', 'Spirits', 'ea', 24, 72),
  ('ZC', 'Water - Sparkling water - 500ml', 'Water', 'ea', 24, 72),
  ('ZC', 'Water - Still Water - 500ml (Bottle)', 'Water', 'ea', 24, 72),
  ('ZC', 'Water - Still Water - 5L (Bottle)', 'Water', 'ea', 24, 72),
  ('ZC', 'Angostura Bitters - 200ml', 'Other', 'ea', 24, 72),
  ('ZC', 'Pimms No1 Cup 750ml', 'Spirits', 'ea', 24, 72),
  ('ZC', 'Oude Meester Peppermint 750ml', 'Spirits', 'ea', 24, 72),
  ('ZC', 'Soft Drinks- Fanta Orange', 'Soft Drinks', 'ea', 24, 72),
  ('ZC', 'Soft Drinks- Coca Cola', 'Soft Drinks', 'ea', 24, 72),
  ('ZC', 'Sparletta Pine Nut', 'Soft Drinks', 'ea', 24, 72),
  ('ZC', 'Other Consumables - Red Wine Glasses - 490ml', 'Consumables', 'ea', 24, 72),
  ('EC', 'Beer - Amstel Lager - 440ml', 'Beer', 'ea', 24, 72),
  ('EC', 'Beer - Amstel Lite - 440ml', 'Beer', 'ea', 24, 72),
  ('EC', 'Beer - Black Label - 330ml', 'Beer', 'ea', 24, 72),
  ('EC', 'Beer - Black Label - 500ml', 'Beer', 'ea', 24, 72),
  ('EC', 'Beer - Corona - 340ml', 'Beer', 'ea', 24, 72),
  ('EC', 'Beer - Castle Light - 340ml (Bottle)', 'Beer', 'ea', 24, 72),
  ('EC', 'Beer - Castle Light - 500ml', 'Beer', 'ea', 24, 72),
  ('EC', 'Beer - Hansa Pilsner - 340ml (Bottle)', 'Beer', 'ea', 24, 72),
  ('EC', 'Beer - Heineken - 330ml (Bottle)', 'Beer', 'ea', 24, 72),
  ('EC', 'Beer - Heineken 0% alcohol', 'Beer', 'ea', 24, 72),
  ('EC', 'Beer - Heineken - 440ml (Can)', 'Beer', 'ea', 24, 72),
  ('EC', 'Beer - St Louis Export/ Lager - 340ml (Can)', 'Beer', 'ea', 24, 72),
  ('EC', 'Beer - St Louis Export/ Lager - 330ml', 'Beer', 'ea', 24, 72),
  ('EC', 'Beer - Windhoek Draught - 440ml (Can)', 'Beer', 'ea', 24, 72),
  ('EC', 'Beer - Windhoek Lager - 440ml (Can)', 'Beer', 'ea', 24, 72),
  ('EC', 'Beer - Windhoek Lager - 330ml (Bottle)', 'Beer', 'ea', 24, 72),
  ('EC', 'Cider - Brutal fruit - 500ml', 'Cider', 'ea', 24, 72),
  ('EC', 'Cider - Savannah Dry - 330ml (Bottle)', 'Cider', 'ea', 24, 72),
  ('EC', 'Cider - Savannah Dry 0% alcohol', 'Cider', 'ea', 24, 72),
  ('EC', 'Cider - Hunters Dry - 330ml', 'Cider', 'ea', 24, 72),
  ('EC', 'Cider - Hunters Dry - 500ml', 'Cider', 'ea', 24, 72),
  ('EC', 'Cider - Hunters Gold - 330ml (Bottle)', 'Cider', 'ea', 24, 72),
  ('EC', 'Cider - Hunters Gold - 440ml', 'Cider', 'ea', 24, 72),
  ('EC', 'Cordial - Grenadine - 750ml', 'Cordial', 'ea', 24, 72),
  ('EC', 'Cordial - Roses Kola Tonic - 750ml', 'Cordial', 'ea', 24, 72),
  ('EC', 'Cordial - Roses Lime - 750ml', 'Cordial', 'ea', 24, 72),
  ('EC', 'Cordial - Roses Passion Fruit - 750ml', 'Cordial', 'ea', 24, 72),
  ('EC', 'Red Wine - The Den"Painted Wolf"Shiraz - 750ml', 'Red Wine', 'ea', 24, 72),
  ('EC', 'Red Wine - The Den"Painted Wolf"Cabernet Sauv - 750 ml', 'Red Wine', 'ea', 24, 72),
  ('EC', 'Red Wine - Chocolate Block - 750 ml (Bottle)', 'Red Wine', 'ea', 24, 72),
  ('EC', 'Red Wine - Fat Bastard Cabanet Sauvignon - 750ml (Bottle)', 'Red Wine', 'ea', 24, 72),
  ('EC', 'Red Wine - Fat Bastard Merlot - 750ml (Bottle)', 'Red Wine', 'ea', 24, 72),
  ('EC', 'Red Wine - Robertson Pinotage - 750ml (Bottle)', 'Red Wine', 'ea', 24, 72),
  ('EC', 'Red Wine - Fat Bastard Shiraz - 750ml (Bottle)', 'Red Wine', 'ea', 24, 72),
  ('EC', 'Red Wine - The Den "Painted Wolf"Chenin Blanc - 750ml (Bottle)', 'Red Wine', 'ea', 24, 72),
  ('EC', 'Red Wine - The Den "Painted Wolf"Dry Rose - 750ml (Bottle)', 'Red Wine', 'ea', 24, 72),
  ('EC', 'Red Wine - The Den"Painted Wolf"Pinotage - 750ml', 'Red Wine', 'ea', 24, 72),
  ('EC', 'Red Wine - Rupert & Rothschildt Classique - 750ml (Bottle)', 'Red Wine', 'ea', 24, 72),
  ('EC', 'Red Wine - Protea Rose - 750ml (Bottle)', 'Red Wine', 'ea', 24, 72),
  ('EC', 'Red Wine - JC Le Roux- 750ml (Bottle)', 'Red Wine', 'ea', 24, 72),
  ('EC', 'Red Wine - Chapel Rose - -750ml', 'Red Wine', 'ea', 24, 72),
  ('EC', 'Red Wine - Namaqua Rose - 5l', 'Red Wine', 'ea', 24, 72),
  ('EC', 'White Wine - La Motte Sauv Blanc - 750ml (Bottle)', 'White Wine', 'ea', 24, 72),
  ('EC', 'White Wine - Warwick F/Lady Sauv Blanc- 750ml (Bottle)', 'White Wine', 'ea', 24, 72),
  ('EC', 'White Wine - Fat Bastard Chardonnay - 750ml (Bottle)', 'White Wine', 'ea', 24, 72),
  ('EC', 'White Wine - Fat Bastard Sauv Blanc - 750ml (Bottle)', 'White Wine', 'ea', 24, 72),
  ('EC', 'White Wine - Van Loveren Chardonnay - 750ml (Bottle)', 'White Wine', 'ea', 24, 72),
  ('EC', 'White Wine - Moet&Chandon Brut Non Vintage - 750ml (Bottle)', 'White Wine', 'ea', 24, 72),
  ('EC', 'White Wine - Porcupine Ridge Chardonnay - 750ml (Bottle)', 'White Wine', 'ea', 24, 72),
  ('EC', 'White Wine - Porcupine Ridge Sauv Blanc - 750ml (Bottle)', 'White Wine', 'ea', 24, 72),
  ('EC', 'White Wine - Simonsig Chenin Blanc - 750ml (Bottle)', 'White Wine', 'ea', 24, 72),
  ('EC', 'White Wine - Van Loveren Sauv Blanc - 750ml (Bottle)', 'White Wine', 'ea', 24, 72),
  ('EC', 'White Wine - 0% simonsig Kaapse vonkel', 'White Wine', 'ea', 24, 72),
  ('EC', 'White Wine - Simonsvelei Brut - 750ml (Bottle)', 'White Wine', 'ea', 24, 72),
  ('EC', 'White Wine - Springfield Life From Stone Sauvignon Blanc - 750ml (Bottle)', 'White Wine', 'ea', 24, 72),
  ('EC', 'Soft Drinks - Appletizer - 330ml (Can)', 'Soft Drinks', 'ea', 24, 72),
  ('EC', 'Soft Drinks - Coke - 330ml (Can)', 'Soft Drinks', 'ea', 24, 72),
  ('EC', 'Soft Drinks - Coke Light/Zero - 330ml (Can)', 'Soft Drinks', 'ea', 24, 72),
  ('EC', 'Soft Drinks - Dry Lemon - 200ml (Can)', 'Soft Drinks', 'ea', 24, 72),
  ('EC', 'Soft Drinks - Ice Tea Peach - 300ml', 'Soft Drinks', 'ea', 24, 72),
  ('EC', 'Soft Drinks - Fanta Orange - 330ml (Can)', 'Soft Drinks', 'ea', 24, 72),
  ('EC', 'Soft Drinks - Fanta Orange - 440ml', 'Soft Drinks', 'ea', 24, 72),
  ('EC', 'Soft Drinks - Fanta Pineapple - 330ml', 'Soft Drinks', 'ea', 24, 72),
  ('EC', 'Soft Drinks - Ginger Ale - 200ml (Can)', 'Soft Drinks', 'ea', 24, 72),
  ('EC', 'Soft Drinks - Cream Soda - 300ml', 'Soft Drinks', 'ea', 24, 72),
  ('EC', 'Soft Drinks - Just Ginger - Gemere - 250ml', 'Soft Drinks', 'ea', 24, 72),
  ('EC', 'Soft Drinks - Stoney Ginger Beer - 2ltr', 'Soft Drinks', 'ea', 24, 72),
  ('EC', 'Soft Drinks - Lemonade - 200ml (Can)', 'Soft Drinks', 'ea', 24, 72),
  ('EC', 'Soft Drinks - Grapetiser', 'Soft Drinks', 'ea', 24, 72),
  ('EC', 'Soft Drinks - Liquifruit - 330ml (Can)', 'Soft Drinks', 'ea', 24, 72),
  ('EC', 'Soft Drinks - Soda - 200ml (Can)', 'Soft Drinks', 'ea', 24, 72),
  ('EC', 'Soft Drinks - Sprite - 330ml', 'Soft Drinks', 'ea', 24, 72),
  ('EC', 'Soft Drinks - Stoney Ginger Beer - 330ml (Can)', 'Soft Drinks', 'ea', 24, 72),
  ('EC', 'Soft Drinks - Tonic - 200ml (Can)', 'Soft Drinks', 'ea', 24, 72),
  ('EC', 'Soft Drinks - Energade/sport drink', 'Soft Drinks', 'ea', 24, 72),
  ('EC', 'Spirits - Amarula - 750ml', 'Spirits', 'ea', 24, 72),
  ('EC', 'Spirits - Amarula - 375ml', 'Spirits', 'ea', 24, 72),
  ('EC', 'Spirits - Amarula - Tot', 'Spirits', 'ea', 24, 72),
  ('EC', 'Spirits - Brandy Klipdrift - Tot', 'Spirits', 'ea', 24, 72),
  ('EC', 'Spirits - Brandy KWV - Tot', 'Spirits', 'ea', 24, 72),
  ('EC', 'Spirits - Brandy Richelieu - Tot', 'Spirits', 'ea', 24, 72),
  ('EC', 'Spirits - Bombay Gin - 750ml - Tots', 'Spirits', 'ea', 24, 72),
  ('EC', 'Spirits - Gin Gordon''s - 750ml', 'Spirits', 'ea', 24, 72),
  ('EC', 'Spirits - Red Heart Rum - 750ml', 'Spirits', 'ea', 24, 72),
  ('EC', 'Spirits - Hennessy - 750 ml', 'Spirits', 'ea', 24, 72),
  ('EC', 'Spirits - Whiskey - Jack Daniels - 750 ml', 'Spirits', 'ea', 24, 72),
  ('EC', 'Spirits - Glenfiddich 12 Year', 'Spirits', 'ea', 24, 72),
  ('EC', 'Spirits - Johnnie Walker Black - 750ml', 'Spirits', 'ea', 24, 72),
  ('EC', 'Spirits - Jagermeister - 750ml - Tot', 'Spirits', 'ea', 24, 72),
  ('EC', 'Spirits - Okavango Gin - 750ml', 'Spirits', 'ea', 24, 72),
  ('EC', 'Spirits - Pushkin vodka - 750ml', 'Spirits', 'ea', 24, 72),
  ('EC', 'Spirits - Rum Captain Morgan Dark', 'Spirits', 'ea', 24, 72),
  ('EC', 'Spirits - Tanqueray', 'Spirits', 'ea', 24, 72),
  ('EC', 'Spirits - Vodka, Smirnoff', 'Spirits', 'ea', 24, 72),
  ('EC', 'Spirits - Whiskey Bell''s', 'Spirits', 'ea', 24, 72),
  ('EC', 'Spirits - Whiskey Famous Grouse', 'Spirits', 'ea', 24, 72),
  ('EC', 'Spirits - Whiskey J&B', 'Spirits', 'ea', 24, 72),
  ('EC', 'Spirits - Whiskey- Bacardi White Rum 750ml', 'Spirits', 'ea', 24, 72),
  ('EC', 'Spirits - Whiskey Jameson', 'Spirits', 'ea', 24, 72),
  ('EC', 'Water - Sparkling water - 500ml', 'Water', 'ea', 24, 72),
  ('EC', 'Water - Still Water - 500ml (Bottle)', 'Water', 'ea', 24, 72),
  ('EC', 'Water - Still Water - 5L (Bottle)', 'Water', 'ea', 24, 72),
  ('EC', 'Angostura Bitters - 200ml', 'Other', 'ea', 24, 72),
  ('EC', 'Pimms No1 Cup 750ml', 'Spirits', 'ea', 24, 72),
  ('EC', 'Oude Meester Peppermint 750ml', 'Spirits', 'ea', 24, 72),
  ('EC', 'Soft Drinks- Fanta Orange', 'Soft Drinks', 'ea', 24, 72),
  ('EC', 'Soft Drinks- Coca Cola', 'Soft Drinks', 'ea', 24, 72),
  ('EC', 'Sparletta Pine Nut', 'Soft Drinks', 'ea', 24, 72),
  ('EC', 'Other Consumables - Red Wine Glasses - 490ml', 'Consumables', 'ea', 24, 72),
  ('SC', 'Beer - Amstel Lager - 440ml', 'Beer', 'ea', 24, 72),
  ('SC', 'Beer - Amstel Lite - 440ml', 'Beer', 'ea', 24, 72),
  ('SC', 'Beer - Black Label - 330ml', 'Beer', 'ea', 24, 72),
  ('SC', 'Beer - Black Label - 500ml', 'Beer', 'ea', 24, 72),
  ('SC', 'Beer - Corona - 340ml', 'Beer', 'ea', 24, 72),
  ('SC', 'Beer - Castle Light - 340ml (Bottle)', 'Beer', 'ea', 24, 72),
  ('SC', 'Beer - Castle Light - 500ml', 'Beer', 'ea', 24, 72),
  ('SC', 'Beer - Hansa Pilsner - 340ml (Bottle)', 'Beer', 'ea', 24, 72),
  ('SC', 'Beer - Heineken - 330ml (Bottle)', 'Beer', 'ea', 24, 72),
  ('SC', 'Beer - Heineken 0% alcohol', 'Beer', 'ea', 24, 72),
  ('SC', 'Beer - Heineken - 440ml (Can)', 'Beer', 'ea', 24, 72),
  ('SC', 'Beer - St Louis Export/ Lager - 340ml (Can)', 'Beer', 'ea', 24, 72),
  ('SC', 'Beer - St Louis Export/ Lager - 330ml', 'Beer', 'ea', 24, 72),
  ('SC', 'Beer - Windhoek Draught - 440ml (Can)', 'Beer', 'ea', 24, 72),
  ('SC', 'Beer - Windhoek Lager - 440ml (Can)', 'Beer', 'ea', 24, 72),
  ('SC', 'Beer - Windhoek Lager - 330ml (Bottle)', 'Beer', 'ea', 24, 72),
  ('SC', 'Cider - Brutal fruit - 500ml', 'Cider', 'ea', 24, 72),
  ('SC', 'Cider - Savannah Dry - 330ml (Bottle)', 'Cider', 'ea', 24, 72),
  ('SC', 'Cider - Savannah Dry 0% alcohol', 'Cider', 'ea', 24, 72),
  ('SC', 'Cider - Hunters Dry - 330ml', 'Cider', 'ea', 24, 72),
  ('SC', 'Cider - Hunters Dry - 500ml', 'Cider', 'ea', 24, 72),
  ('SC', 'Cider - Hunters Gold - 330ml (Bottle)', 'Cider', 'ea', 24, 72),
  ('SC', 'Cider - Hunters Gold - 440ml', 'Cider', 'ea', 24, 72),
  ('SC', 'Cordial - Grenadine - 750ml', 'Cordial', 'ea', 24, 72),
  ('SC', 'Cordial - Roses Kola Tonic - 750ml', 'Cordial', 'ea', 24, 72),
  ('SC', 'Cordial - Roses Lime - 750ml', 'Cordial', 'ea', 24, 72),
  ('SC', 'Cordial - Roses Passion Fruit - 750ml', 'Cordial', 'ea', 24, 72),
  ('SC', 'Red Wine - The Den"Painted Wolf"Shiraz - 750ml', 'Red Wine', 'ea', 24, 72),
  ('SC', 'Red Wine - The Den"Painted Wolf"Cabernet Sauv - 750 ml', 'Red Wine', 'ea', 24, 72),
  ('SC', 'Red Wine - Chocolate Block - 750 ml (Bottle)', 'Red Wine', 'ea', 24, 72),
  ('SC', 'Red Wine - Fat Bastard Cabanet Sauvignon - 750ml (Bottle)', 'Red Wine', 'ea', 24, 72),
  ('SC', 'Red Wine - Fat Bastard Merlot - 750ml (Bottle)', 'Red Wine', 'ea', 24, 72),
  ('SC', 'Red Wine - Robertson Pinotage - 750ml (Bottle)', 'Red Wine', 'ea', 24, 72),
  ('SC', 'Red Wine - Fat Bastard Shiraz - 750ml (Bottle)', 'Red Wine', 'ea', 24, 72),
  ('SC', 'Red Wine - The Den "Painted Wolf"Chenin Blanc - 750ml (Bottle)', 'Red Wine', 'ea', 24, 72),
  ('SC', 'Red Wine - The Den "Painted Wolf"Dry Rose - 750ml (Bottle)', 'Red Wine', 'ea', 24, 72),
  ('SC', 'Red Wine - The Den"Painted Wolf"Pinotage - 750ml', 'Red Wine', 'ea', 24, 72),
  ('SC', 'Red Wine - Rupert & Rothschildt Classique - 750ml (Bottle)', 'Red Wine', 'ea', 24, 72),
  ('SC', 'Red Wine - Protea Rose - 750ml (Bottle)', 'Red Wine', 'ea', 24, 72),
  ('SC', 'Red Wine - JC Le Roux- 750ml (Bottle)', 'Red Wine', 'ea', 24, 72),
  ('SC', 'Red Wine - Chapel Rose - -750ml', 'Red Wine', 'ea', 24, 72),
  ('SC', 'Red Wine - Namaqua Rose - 5l', 'Red Wine', 'ea', 24, 72),
  ('SC', 'White Wine - La Motte Sauv Blanc - 750ml (Bottle)', 'White Wine', 'ea', 24, 72),
  ('SC', 'White Wine - Warwick F/Lady Sauv Blanc- 750ml (Bottle)', 'White Wine', 'ea', 24, 72),
  ('SC', 'White Wine - Fat Bastard Chardonnay - 750ml (Bottle)', 'White Wine', 'ea', 24, 72),
  ('SC', 'White Wine - Fat Bastard Sauv Blanc - 750ml (Bottle)', 'White Wine', 'ea', 24, 72),
  ('SC', 'White Wine - Van Loveren Chardonnay - 750ml (Bottle)', 'White Wine', 'ea', 24, 72),
  ('SC', 'White Wine - Moet&Chandon Brut Non Vintage - 750ml (Bottle)', 'White Wine', 'ea', 24, 72),
  ('SC', 'White Wine - Porcupine Ridge Chardonnay - 750ml (Bottle)', 'White Wine', 'ea', 24, 72),
  ('SC', 'White Wine - Porcupine Ridge Sauv Blanc - 750ml (Bottle)', 'White Wine', 'ea', 24, 72),
  ('SC', 'White Wine - Simonsig Chenin Blanc - 750ml (Bottle)', 'White Wine', 'ea', 24, 72),
  ('SC', 'White Wine - Van Loveren Sauv Blanc - 750ml (Bottle)', 'White Wine', 'ea', 24, 72),
  ('SC', 'White Wine - 0% simonsig Kaapse vonkel', 'White Wine', 'ea', 24, 72),
  ('SC', 'White Wine - Simonsvelei Brut - 750ml (Bottle)', 'White Wine', 'ea', 24, 72),
  ('SC', 'White Wine - Springfield Life From Stone Sauvignon Blanc - 750ml (Bottle)', 'White Wine', 'ea', 24, 72),
  ('SC', 'Soft Drinks - Appletizer - 330ml (Can)', 'Soft Drinks', 'ea', 24, 72),
  ('SC', 'Soft Drinks - Coke - 330ml (Can)', 'Soft Drinks', 'ea', 24, 72),
  ('SC', 'Soft Drinks - Coke Light/Zero - 330ml (Can)', 'Soft Drinks', 'ea', 24, 72),
  ('SC', 'Soft Drinks - Dry Lemon - 200ml (Can)', 'Soft Drinks', 'ea', 24, 72),
  ('SC', 'Soft Drinks - Ice Tea Peach - 300ml', 'Soft Drinks', 'ea', 24, 72),
  ('SC', 'Soft Drinks - Fanta Orange - 330ml (Can)', 'Soft Drinks', 'ea', 24, 72),
  ('SC', 'Soft Drinks - Fanta Orange - 440ml', 'Soft Drinks', 'ea', 24, 72),
  ('SC', 'Soft Drinks - Fanta Pineapple - 330ml', 'Soft Drinks', 'ea', 24, 72),
  ('SC', 'Soft Drinks - Ginger Ale - 200ml (Can)', 'Soft Drinks', 'ea', 24, 72),
  ('SC', 'Soft Drinks - Cream Soda - 300ml', 'Soft Drinks', 'ea', 24, 72),
  ('SC', 'Soft Drinks - Just Ginger - Gemere - 250ml', 'Soft Drinks', 'ea', 24, 72),
  ('SC', 'Soft Drinks - Stoney Ginger Beer - 2ltr', 'Soft Drinks', 'ea', 24, 72),
  ('SC', 'Soft Drinks - Lemonade - 200ml (Can)', 'Soft Drinks', 'ea', 24, 72),
  ('SC', 'Soft Drinks - Grapetiser', 'Soft Drinks', 'ea', 24, 72),
  ('SC', 'Soft Drinks - Liquifruit - 330ml (Can)', 'Soft Drinks', 'ea', 24, 72),
  ('SC', 'Soft Drinks - Soda - 200ml (Can)', 'Soft Drinks', 'ea', 24, 72),
  ('SC', 'Soft Drinks - Sprite - 330ml', 'Soft Drinks', 'ea', 24, 72),
  ('SC', 'Soft Drinks - Stoney Ginger Beer - 330ml (Can)', 'Soft Drinks', 'ea', 24, 72),
  ('SC', 'Soft Drinks - Tonic - 200ml (Can)', 'Soft Drinks', 'ea', 24, 72),
  ('SC', 'Soft Drinks - Energade/sport drink', 'Soft Drinks', 'ea', 24, 72),
  ('SC', 'Spirits - Amarula - 750ml', 'Spirits', 'ea', 24, 72),
  ('SC', 'Spirits - Amarula - 375ml', 'Spirits', 'ea', 24, 72),
  ('SC', 'Spirits - Amarula - Tot', 'Spirits', 'ea', 24, 72),
  ('SC', 'Spirits - Brandy Klipdrift - Tot', 'Spirits', 'ea', 24, 72),
  ('SC', 'Spirits - Brandy KWV - Tot', 'Spirits', 'ea', 24, 72),
  ('SC', 'Spirits - Brandy Richelieu - Tot', 'Spirits', 'ea', 24, 72),
  ('SC', 'Spirits - Bombay Gin - 750ml - Tots', 'Spirits', 'ea', 24, 72),
  ('SC', 'Spirits - Gin Gordon''s - 750ml', 'Spirits', 'ea', 24, 72),
  ('SC', 'Spirits - Red Heart Rum - 750ml', 'Spirits', 'ea', 24, 72),
  ('SC', 'Spirits - Hennessy - 750 ml', 'Spirits', 'ea', 24, 72),
  ('SC', 'Spirits - Whiskey - Jack Daniels - 750 ml', 'Spirits', 'ea', 24, 72),
  ('SC', 'Spirits - Glenfiddich 12 Year', 'Spirits', 'ea', 24, 72),
  ('SC', 'Spirits - Johnnie Walker Black - 750ml', 'Spirits', 'ea', 24, 72),
  ('SC', 'Spirits - Jagermeister - 750ml - Tot', 'Spirits', 'ea', 24, 72),
  ('SC', 'Spirits - Okavango Gin - 750ml', 'Spirits', 'ea', 24, 72),
  ('SC', 'Spirits - Pushkin vodka - 750ml', 'Spirits', 'ea', 24, 72),
  ('SC', 'Spirits - Rum Captain Morgan Dark', 'Spirits', 'ea', 24, 72),
  ('SC', 'Spirits - Tanqueray', 'Spirits', 'ea', 24, 72),
  ('SC', 'Spirits - Vodka, Smirnoff', 'Spirits', 'ea', 24, 72),
  ('SC', 'Spirits - Whiskey Bell''s', 'Spirits', 'ea', 24, 72),
  ('SC', 'Spirits - Whiskey Famous Grouse', 'Spirits', 'ea', 24, 72),
  ('SC', 'Spirits - Whiskey J&B', 'Spirits', 'ea', 24, 72),
  ('SC', 'Spirits - Whiskey- Bacardi White Rum 750ml', 'Spirits', 'ea', 24, 72),
  ('SC', 'Spirits - Whiskey Jameson', 'Spirits', 'ea', 24, 72),
  ('SC', 'Water - Sparkling water - 500ml', 'Water', 'ea', 24, 72),
  ('SC', 'Water - Still Water - 500ml (Bottle)', 'Water', 'ea', 24, 72),
  ('SC', 'Water - Still Water - 5L (Bottle)', 'Water', 'ea', 24, 72),
  ('SC', 'Angostura Bitters - 200ml', 'Other', 'ea', 24, 72),
  ('SC', 'Pimms No1 Cup 750ml', 'Spirits', 'ea', 24, 72),
  ('SC', 'Oude Meester Peppermint 750ml', 'Spirits', 'ea', 24, 72),
  ('SC', 'Soft Drinks- Fanta Orange', 'Soft Drinks', 'ea', 24, 72),
  ('SC', 'Soft Drinks- Coca Cola', 'Soft Drinks', 'ea', 24, 72),
  ('SC', 'Sparletta Pine Nut', 'Soft Drinks', 'ea', 24, 72),
  ('SC', 'Other Consumables - Red Wine Glasses - 490ml', 'Consumables', 'ea', 24, 72);
